[build-system]
requires = ["hatchling>=1.21.0"]
build-backend = "hatchling.build"

[project]
name = "swarm-agent-sdk"
version = "0.1.0"
description = "MCP-based Agent SDK for the Agentic Trading Swarm"
authors = [{name = "Agentic Swarm", email = "eng@example.com"}]
requires-python = ">=3.9"
dependencies = [
  "pydantic>=2.7",
  "httpx>=0.27",
  "websockets>=12.0",
  "tenacity>=8.2",
  "pyyaml>=6.0",
]

[project.optional-dependencies]
dev = ["ruff", "pytest", "mypy", "types-PyYAML"]

[tool.hatch.build.targets.wheel]
packages = ["src/swarm_agent_sdk"]
